CREATE DATABASE WEBAPP
GO

USE WEBAPP
GO

CREATE TABLE PESSOA_AGENDA (
    ID INT IDENTITY(1,1),
    NOME VARCHAR(100),
    TELEFONE VARCHAR(10),
    EMAIL VARCHAR(50),
    ENDERECO VARCHAR(100),
    DATANASC DATETIME
)
GO

CREATE PROC SP_INSERE_PESSOA (
    @NOME VARCHAR(100),
    @TELEFONE VARCHAR(10),
    @EMAIL VARCHAR(50),
    @ENDERECO VARCHAR(100),
    @DATANASC DATETIME
) AS BEGIN
    INSERT INTO PESSOA_AGENDA VALUES (@NOME, @TELEFONE, @EMAIL, @ENDERECO, @DATANASC)
END
GO

CREATE PROC SP_ATUALIZA_PESSOA (
    @ID INT,
    @NOME VARCHAR(100),
    @TELEFONE VARCHAR(10),
    @EMAIL VARCHAR(50),
    @ENDERECO VARCHAR(100),
    @DATANASC DATETIME
) AS BEGIN
    UPDATE PESSOA_AGENDA SET NOME = @NOME,
        TELEFONE = @TELEFONE, 
        EMAIL = @EMAIL,
        ENDERECO = @ENDERECO,
        DATANASC = @DATANASC
    WHERE ID = @ID
END
GO

CREATE PROC SP_EXCLUI_PESSOA (
    @ID INT
) AS BEGIN
    DELETE FROM PESSOA_AGENDA WHERE ID = @ID
END
GO

CREATE PROC SP_CONSULTA_PESSOA (
    @ID INT
) AS BEGIN
    SELECT * FROM PESSOA_AGENDA WHERE ID = @ID
END
GO

CREATE PROC SP_LISTA_PESSOA
AS BEGIN
    SELECT * FROM PESSOA_AGENDA
END
GO